### ISSUE TITLE
Allow dynamic focus target

### ISSUE THREAD

**Issue by daun** [swup/a11y-plugin#26]
**Describe the problem**

- Some visits don't need to reset focus to the `main` element, e.g. fragment visits like filter UIs
- Ideally, the custom focus target could be overwritten per visit
- The fragment plugin and users can then just set `visit.focus = '#list'` or similar

**Describe the proposed solution**

- New key in visit object: `visit.focus` — or maybe nested/grouped somewhere?
- New hook `content:focus` that can be replaced

**How important is this feature to you?**

- [ ] Nice to have
- [x] Would make my life a lot easier
- [ ] I cannot use swup without it

**Comment by hirasso** [comment]
Very nice idea!
