### ISSUE TITLE
Create a demo site

### ISSUE THREAD

**Issue by daun** [swup/a11y-plugin#51]
### Describe the problem 🧐

- Testing a11y with swup could be a easier if we had a standardized demo app

### Describe the propsed solution 😎

- Create a demo site that can also serve as an interactive test suite

### Prior art

- [Ember A11y Demo App](https://github.com/ember-a11y/a11y-demo-app)
- [Testing A11y Demo App](https://github.com/marcysutton/a11y-demo-app)
- [Deque University A11y Demo Sites](https://dequeuniversity.com/demo/)

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
Alternatively: Couldn't we just use the [docs](https://swup.js.org) as the demo site? As a user, I'd read that as the best advertisement.

**Comment by hirasso** [comment]
Ah nice!
