### ISSUE TITLE
[Bug]: Language fallback no longer working

### ISSUE THREAD

**Issue by daun** [swup/a11y-plugin#58]
### What did you expect? 🧐

An undefined language should result in the announcement using the provided fallback.

### What actually happened? 😵‍💫

No announcement is made if the language is not defined in the options. This started happening in 4.5.1, specifically after [this pull request](https://github.com/swup/a11y-plugin/pull/46) was merged. The part that seemed redundant was actually the relevant implementation of the fallback: `announcements['*']`.

I'll make a note to fix and test this in the test branch that's currently in progress, just flagging it here so we don't forget.

### Swup and plugin versions 📝

- swup: *
- a11y plugin: 4.5.1

### URL to minimal reproduction 🔗

https://github.com/swup/a11y-plugin/pull/46/files

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
Great that you have caught this so early! We really need a test suite.
